---
- hosts: bsp-wa-1a
  #gather_facts: True
  become: true
  tasks:
          - name: Download cloudwatch-agent package
            shell: wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm

          - name: Install cloudwatch-agent
            yum:
               name: ./amazon-cloudwatch-agent.rpm
               state: present

# nanti jalanin dengan "sudo ansible-playbook cloudwatch-agent.yml -kK"
